title: mayhem and project eve
author: amy perkins
email: evesproject@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A project that uses blockchain and the power of humankindess to bring education and help during crisis, to everyone on the planet. A non for profit company that promotes other non-for-profit agencies and organizations. And me. A homeless girl on a mission to do my part to change the world before I run out of time.

# social links
https://github.com/organizations/Arkang3l/settings/profile
github_username:  Afalon@github

show_excerpts: true # set to false to remove excerpts on the homepage
